### PR TITLE
Added: Multimedia Elzero web school

### PR DESCRIPTION
**Pull request by OsamaRab3**
### What is your contribution type?

- [x] Suggest an Awesome item.
- [ ] Web site maintenance.
- [ ] Other.

### What's in this PR?
This pull request introduce add first item in the Channels category which is Elzero web school .

### Checklist

- [x] Ensure to check our [Contribution Criteria](../blob/main/CONTRIBUTING.md#criteria).
- [x] The contribution doesn't already exist (you can use [search functionality](https://awesome-arabic-speakers.dev/search/)).
- [x] The contribution is provided in both Arabic and English.

### CODE REVIEW

**Comment by aabouzaid** [comment]
@OsamaRab3 Thanks for your contribution :raised_hands: 

Please rebase to the main branch; there are a couple of missing commits.

Also, let's find a better cover.

**Comment by aabouzaid** [comment]
@OsamaElzero, do you have one line of this image but in a higher quality?
elzero

**Comment by OsamaRab3** [comment]
> @OsamaElzero, do you have one line of this image but in a higher quality? elzero

Do you think this picture looks good?
image

**Comment by aabouzaid** [comment]
Yeah, we can use the left side.
I will make the cover once you rebase to the main branch.

**Review by aabouzaid — CHANGES_REQUESTED** [review]
I will review it again after the changes are made.

**Comment by OsamaElzero** [comment]
> > @OsamaElzero, do you have one line of this image but in a higher quality? elzero
> 
> Do you think this picture looks good? image

Sorry for late answer
its ok for now till i create the new identity <3

**Pull request closed without merging**
