### PR TITLE
feat: basic layout change

### PR DESCRIPTION
**Pull request by MrViometal**
### What is your contribution type?

- [ ] Suggest an Awesome item.
- [x] Web site maintenance.
- [ ] Other.

### What's in this PR?

basic layout shift for laptop (min-width: 960px) 

### Checklist

- [ ] Ensure to check our [Contribution Criteria](./CONTRIBUTING.md#criteria).
- [ ] The contribution doesn't already exist (you can use [search functionality](https://awesome-arabic-speakers.dev/search/)).
- [ ] The contribution is provided in both Arabic and English.

### CODE REVIEW

**Comment by aabouzaid** [comment]
Looks great :star_struck: 

I made a small change:
- Increased the top padding of the main menu.
- Removed the search and archive as they show in the main menu at the top.
- Moved the social links.
- Increased the pagination to 6 to fill all grid slots.

Before:

awesome-arabic-speakers-pull-6-before

After:
awesome-arabic-speakers-pull-6-after

**Comment by MrViometal** [comment]
@aabouzaid thanks for that Ahmed 🙏🏼 
I have just fixed the social media positioning as we discussed, and also fixed a problem with the main menu alignment

**Comment by aabouzaid** [comment]
Great :raised_hands: 

Thanks for your effort @MrViometal :rocket: 

I made another 2 small changes:
- Added the site meta at the top (site name and description).
- Transformed the logo in the dark mode (because of the logo colors, it wasn't clear in the dark mode).

Awesome_Arabic_Speakers_iter_1 2

**Review by aabouzaid — APPROVED** [review]
Great work :rocket:

**Pull request merged**
