### PR TITLE
Added: Multimedia - Elzero Web School

### PR DESCRIPTION
**Pull request by OsamaRab3**
### What is your contribution type?

- [x] Suggest an Awesome item - https://github.com/sahaba-ai/awesome-arabic-speakers/issues/8
- [ ] Web site maintenance.
- [ ] Other.

### What's in this PR?
This pull request introduce add first item in the Channels category which is Elzero web school .

### Checklist

- [x] Ensure to check our [Contribution Criteria](../blob/main/CONTRIBUTING.md#criteria).
- [x] The contribution doesn't already exist (you can use [search functionality](https://awesome-arabic-speakers.dev/search/)).
- [x] The contribution is provided in both Arabic and English.

### CODE REVIEW

**Comment by aabouzaid** [comment]
@OsamaRab3 no need to open a new PR.
Please reuse the PR #16 by pushing your changes to the old branch.

```
git checkout elzero
git reset --hard multimedia
git push --force
```

**Comment by OsamaRab3** [comment]
> no need to open a new PR.
> Please reuse the PR #16 by pushing your changes to the old branch.


I deleted the fork and cloned the repository again to keep the git graph clean and organized. If you don't mind, I will add the  techvault

**Comment by aabouzaid** [comment]
> I deleted the fork and cloned the repository again to keep the git graph clean and organized.

It's possible to do that without deleting the fork (read about it just for you).

We can use this PR for now, but please use the same branch for the next PRs (you can reset it as mentioned above).

> If you don't mind, I will add the techvault

You have it :raised_hands:

**Comment by OsamaRab3** [comment]
Thank you for your message and clarification! I'm currently working on adding the Big Data

**Comment by aabouzaid** [comment]
@OsamaRab3 Each contribution should have its own PR. Please open a new one for other resources.

**Comment by OsamaRab3** [comment]
> @OsamaRab3 Each contribution should have its own PR. Please open a new one for other resources.

Should I open a new PR for techvault? Could we possibly change the title of the PR to include both channel

**Comment by aabouzaid** [comment]
> > @OsamaRab3 Each contribution should have its own PR. Please open a new one for other resources.
> 
> Should I open a new PR for techvault? Could we possibly change the title of the PR to include both channel

For better organization, it should be a PR per contribution; otherwise, it will be a mess.

**Comment by OsamaRab3** [comment]
Are there any additional changes or updates that need on Elzero web school. If not, I will go ahead and open a new PR

**Comment by aabouzaid** [comment]
> Are there any additional changes or updates that need on Elzero web school. If not, I will go ahead and open a new PR

Be sure to back up the changes for `Tech Vault` because they will be removed.

**Comment by OsamaRab3** [comment]
> > Are there any additional changes or updates that need on Elzero web school. If not, I will go ahead and open a new PR
> 
> Be sure to back up the changes for `Tech Vault` because they will be removed.

Understood

**Review by aabouzaid — APPROVED** [review]
@OsamaRab3 Thanks for your contribution :raised_hands: 
I made some enhancements, so it's ready to merge.

**Pull request merged**
